# Generated by Django 4.0.4 on 2022-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_at', models.DateTimeField()),
                ('btc', models.FloatField(null=True)),
                ('xmr', models.FloatField(null=True)),
                ('arima', models.FloatField(null=True)),
                ('garch', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tick_at'],
            },
        ),
    ]
