# Generated by Django 4.0.4 on 2022-06-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='eth',
            field=models.FloatField(null=True),
        ),
    ]
