# Generated by Django 4.0.4 on 2022-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticker_bnb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='ada',
            field=models.FloatField(null=True),
        ),
    ]
