# Generated by Django 4.0.4 on 2022-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ticker_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='doge',
            field=models.FloatField(null=True),
        ),
    ]
