# Generated by Django 4.0.4 on 2022-06-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticker_doge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='dot',
            field=models.FloatField(null=True),
        ),
    ]
