# Generated by Django 4.0.4 on 2022-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ticker_dot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='dot',
        ),
        migrations.AddField(
            model_name='ticker',
            name='trx',
            field=models.FloatField(null=True),
        ),
    ]
