# Generated by Django 4.0.4 on 2022-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ticker_dot_ticker_trx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='sol',
        ),
        migrations.AddField(
            model_name='ticker',
            name='avax',
            field=models.FloatField(null=True),
        ),
    ]
