# Generated by Django 4.0.4 on 2022-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ticker_sol_ticker_avax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='avax',
        ),
        migrations.AddField(
            model_name='ticker',
            name='matic',
            field=models.FloatField(null=True),
        ),
    ]
