# Generated by Django 4.0.4 on 2022-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_ticker_avax_ticker_matic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='uni',
            field=models.FloatField(null=True),
        ),
    ]
