# Generated by Django 4.0.4 on 2022-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ticker_ftt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='doge',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='ftt',
        ),
        migrations.AddField(
            model_name='ticker',
            name='link',
            field=models.FloatField(null=True),
        ),
    ]
