# Generated by Django 4.0.4 on 2022-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_ticker_doge_remove_ticker_ftt_ticker_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='xlm',
            field=models.FloatField(null=True),
        ),
    ]
