# Generated by Django 4.0.4 on 2022-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ticker_cro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='cro',
        ),
        migrations.AddField(
            model_name='ticker',
            name='algo',
            field=models.FloatField(null=True),
        ),
    ]
