# Generated by Django 4.0.4 on 2022-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_ticker_cro_ticker_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='doge',
            field=models.FloatField(null=True),
        ),
    ]
