# Generated by Django 4.0.4 on 2022-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_ticker_doge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='atom',
            field=models.FloatField(null=True),
        ),
    ]
