# Generated by Django 4.0.4 on 2022-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_ticker_atom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='bch',
            field=models.FloatField(null=True),
        ),
    ]
