# Generated by Django 4.0.4 on 2022-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ticker_bch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='bch',
        ),
        migrations.AddField(
            model_name='ticker',
            name='etc',
            field=models.FloatField(null=True),
        ),
    ]
