# Generated by Django 4.0.4 on 2022-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_ticker_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='mana',
            field=models.FloatField(null=True),
        ),
    ]
