# Generated by Django 4.0.4 on 2022-06-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_ticker_mana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='mana',
        ),
        migrations.AddField(
            model_name='ticker',
            name='flow',
            field=models.FloatField(null=True),
        ),
    ]
