# Generated by Django 4.0.4 on 2022-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_ticker_mana_ticker_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='flow',
        ),
        migrations.AddField(
            model_name='ticker',
            name='hbar',
            field=models.FloatField(null=True),
        ),
    ]
