# Generated by Django 4.0.4 on 2022-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_ticker_flow_ticker_hbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='theta',
            field=models.FloatField(null=True),
        ),
    ]
