# Generated by Django 4.0.4 on 2022-06-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_ticker_egld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='egld',
        ),
        migrations.AddField(
            model_name='ticker',
            name='kcs',
            field=models.FloatField(null=True),
        ),
    ]
