# Generated by Django 4.0.4 on 2022-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_ticker_egld_ticker_kcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='kcs',
        ),
        migrations.AddField(
            model_name='ticker',
            name='eos',
            field=models.FloatField(null=True),
        ),
    ]
