# Generated by Django 4.0.4 on 2022-07-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_ticker_kcs_ticker_eos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='mkr',
            field=models.FloatField(null=True),
        ),
    ]
