# Generated by Django 4.0.4 on 2022-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_ticker_mkr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='mkr',
        ),
        migrations.AddField(
            model_name='ticker',
            name='aave',
            field=models.FloatField(null=True),
        ),
    ]
