# Generated by Django 4.0.4 on 2022-07-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_ticker_mkr_ticker_aave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='aave',
        ),
        migrations.AddField(
            model_name='ticker',
            name='kcs',
            field=models.FloatField(null=True),
        ),
    ]
