# Generated by Django 4.0.4 on 2022-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_ticker_aave_ticker_kcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='kcs',
        ),
        migrations.AddField(
            model_name='ticker',
            name='zec',
            field=models.FloatField(null=True),
        ),
    ]
