# Generated by Django 4.0.4 on 2022-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_ticker_mkr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='mkr',
        ),
        migrations.AddField(
            model_name='ticker',
            name='btt',
            field=models.FloatField(null=True),
        ),
    ]
