# Generated by Django 4.0.4 on 2022-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_ticker_mkr_ticker_btt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='btt',
        ),
        migrations.AddField(
            model_name='ticker',
            name='miota',
            field=models.FloatField(null=True),
        ),
    ]
