# Generated by Django 4.0.4 on 2022-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_ticker_miota_ticker_rune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='rune',
        ),
        migrations.AddField(
            model_name='ticker',
            name='grt',
            field=models.FloatField(null=True),
        ),
    ]
