# Generated by Django 4.0.4 on 2022-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_ticker_grt_ticker_ht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='ht',
        ),
        migrations.AddField(
            model_name='ticker',
            name='klay',
            field=models.FloatField(null=True),
        ),
    ]
