# Generated by Django 4.0.4 on 2022-07-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_ticker_ht_ticker_klay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='klay',
        ),
    ]
