# Generated by Django 4.0.4 on 2022-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_ticker_klay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='abt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='aby',
            field=models.FloatField(null=True),
        ),
    ]
