# Generated by Django 4.0.4 on 2022-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_ticker_abt_ticker_aby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='abt',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='aby',
        ),
        migrations.AddField(
            model_name='ticker',
            name='ac',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='act',
            field=models.FloatField(null=True),
        ),
    ]
