# Generated by Django 4.0.4 on 2024-03-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_ticker_abt_remove_ticker_aby_ticker_ac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='act',
        ),
    ]
