# Generated by Django 4.0.4 on 2022-07-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('precision', models.IntegerField()),
                ('confirms', models.IntegerField()),
                ('contract_address', models.CharField(max_length=250, null=True)),
                ('withdrawal_min_size', models.FloatField()),
                ('withdrawal_min_fee', models.FloatField()),
                ('is_withdraw_enabled', models.BooleanField()),
                ('is_deposit_enabled', models.BooleanField()),
                ('is_margin_enabled', models.BooleanField()),
                ('is_debit_enabled', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('base_min_size', models.FloatField()),
                ('quote_min_size', models.FloatField()),
                ('base_max_size', models.FloatField()),
                ('quote_max_size', models.FloatField()),
                ('base_increment', models.FloatField()),
                ('quote_increment', models.FloatField()),
                ('price_increment', models.FloatField()),
                ('price_limit_rate', models.FloatField()),
                ('enabled_trading', models.BooleanField()),
                ('is_margin_enabled', models.BooleanField()),
                ('min_funds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_symbols', to='kc.currency')),
                ('fee_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_symbols', to='kc.currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='kc.market')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_symbols', to='kc.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.PositiveBigIntegerField(unique=True)),
                ('minute', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('time', models.PositiveBigIntegerField()),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('best_bid_size', models.FloatField()),
                ('best_bid', models.FloatField()),
                ('best_ask_size', models.FloatField()),
                ('best_ask', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='kc.symbol')),
                ('tick_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='kc.timestamp')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
