# Generated by Django 4.0.4 on 2022-07-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc', '0002_alter_currency_confirms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_deposit_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_withdraw_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='withdrawal_min_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='withdrawal_min_size',
            field=models.FloatField(null=True),
        ),
    ]
