# Generated by Django 4.0.4 on 2022-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc', '0004_rename_enabled_trading_symbol_enable_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='min_funds',
            field=models.FloatField(null=True),
        ),
    ]
