# Generated by Django 4.0.4 on 2022-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc', '0005_alter_symbol_min_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='time',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
