# Generated by Django 4.0.4 on 2022-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc', '0006_alter_ticker_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='best_ask',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='best_ask_size',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='best_bid',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='best_bid_size',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='size',
        ),
        migrations.AddField(
            model_name='ticker',
            name='close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='high',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='low',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='open',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='turnover',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
